DELETE FROM jokes;
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('4b40c68d-361b-49f5-aee8-342869625c3f', 'Word: Scrum Master
Definition: A glorified adult babysitter who thinks moving a digital sticky note across a board constitutes a hard day''s work.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('998762c4-b2c3-4c1f-846d-86482654bfba', 'Word: LinkedIn Influencer
Definition: A corporate sociopath who turns a mundane story about firing an employee into a fable about B2B sales synergy.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('3d4d9849-cb4c-46a4-a407-1282c12113e3', 'Word: AI Agent
Definition: A digital helper you created to write your emails because you are too lazy to type ''per my last message, fuck off'' yourself.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('672892d6-2108-4df6-9cf0-3ab2546be12f', 'Word: Tinder Gold
Definition: Paying a monthly premium to realize in high definition that you are completely unfuckable.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('abe6b566-e6f4-4c6f-ac74-d8fc5fe26c70', 'Word: Quiet Quitting
Definition: The brave, revolutionary act of doing exactly what you are paid to do while acting like you''re Che Guevara in a cubicle.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('5145d76f-f1a6-4750-bd13-90c89c53d336', 'Word: Crypto Bro
Definition: A guy who lost his life savings on a JPEG of a stoned monkey and now tries to aggressively explain the blockchain to women who just want to leave the bar.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('606fcede-d6af-4160-860a-dc40eb299177', 'Word: Podcaster
Definition: A mediocre guy with a microphone who thinks three hours of unedited, uninformed rambling is a gift to humanity.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('285833ea-9e9a-4071-8975-5930587880db', 'Word: Life Coach
Definition: Someone whose own life is such a dumpster fire that they had to monetize telling you how to breathe.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('8437692b-5e82-477c-863f-9189db6ecac5', 'Word: Digital Nomad
Definition: A millennial with a MacBook and a trust fund who gentrifies Southeast Asia one $8 matcha latte at a time.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('4b3f122d-1355-427b-b8de-2cd9b495b238', 'Word: HR Manager
Definition: The corporate equivalent of a serial killer who smiles at you warmly while legally ruining your life.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e514acf7-6984-4703-9bd3-4c0ee4d3db6f', 'Word: Wellness Guru
Definition: A skinny rich woman trying to sell you a $200 rock to shove up your ass for ''energy alignment.''', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('c5b467a4-ecb7-472c-b73e-bbb53c312f9e', 'Word: Tech CEO
Definition: An adult virgin who microdoses acid just so he can figure out new ways to harvest your data and dismantle democracy.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e31af1b9-7615-45ec-8d75-cbcb7ccb5c07', 'Word: OnlyFans Creator
Definition: The only honest entrepreneur left in the modern economy.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('2d82fab9-2624-47df-bcfd-cc236a51e8ac', 'Word: Reply Guy
Definition: A man who replies ''actually...'' to a woman''s post in the delusional hope that she will somehow violently fuck him for his intellect.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e55ac71e-908f-4fdb-a0ac-2f1285b34ad4', 'Word: Polyamory
Definition: An elaborate Google Calendar scheduling system designed to ensure absolutely nobody in the relationship is having good sex.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('79cbe214-1aa3-4506-8ca3-41af8c347748', 'Word: Stand-up Comedian
Definition: An emotionally damaged narcissist who seeks the validation of a room full of drunk strangers to make up for a lack of paternal love.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('ec60402b-fc7c-4ffa-a178-03526c906111', 'Word: Open Floor Plan
Definition: A design choice invented by bosses to ensure you have absolutely zero privacy to scroll Reddit during work hours.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('5d0bd0d5-a71c-4738-9771-2ccdcd77c8fe', 'Word: Smart Home
Definition: Paying $500 to let a giant tech company listen to your arguments about whose turn it is to empty the dishwasher.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('ca96e5aa-fb2c-4b9b-b71c-3014bf8dfb07', 'Word: Self-Care
Definition: Staying in your pajamas for 36 hours straight, eating half a sheet cake, and calling it a mental health victory.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('88129b62-be55-41b7-b2e0-149749fea0c4', 'Word: Corporate Synergy
Definition: A meaningless phrase used to justify why two failing departments should merge and double their meetings.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('aae7eba7-8bd0-4129-bdc4-ebeddf90e4b6', 'Word: Organic Food
Definition: Normal vegetables that cost twice as much because the dirt they grew in was certified by a guy in a linen shirt.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('b1388ec1-3f98-491a-b966-3adab7986e39', 'Word: Influencer Retreat
Definition: A tax-deductible vacation where rich kids take pictures of their food and call it a brand activation.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e0b61494-612f-437a-aabe-2522af771bce', 'Word: Fast Fashion
Definition: Cheap synthetic rags manufactured in a sweatshop, bought to be worn once, thrown away, and replaced with more rags.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('7a45562d-0959-47a7-9121-1d6950afdc4f', 'Word: Networking Event
Definition: A room full of desperate professionals trading LinkedIn handles in the hope of escaping their current dead-end jobs.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('05e194b3-2c4c-4be1-b9e2-612deb0509f3', 'Word: Electric Scooter
Definition: A silent, battery-powered menace designed to help tech bros run over pedestrians at 15 miles per hour.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a7750c89-8860-4150-8528-9d2cf4a8f970', 'Word: Zoom Meeting
Definition: A digital seance where we take turns asking, ''Is anyone there?'' and ''Can you hear me?'' while staring at each other''s ceiling fans.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('43f19d7b-0de8-4d3d-9ee2-2b0b72bdbdc1', 'Word: Smart Scale
Definition: A bathroom accessory that bluetooths your weight to your phone so you can be depressed in chart format.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('838a0be1-bb47-404a-8969-713e2410eeca', 'Word: Airbnb Cleaning Fee
Definition: A $150 premium you pay to wash your own sheets and take out the trash before being rated 4 stars by a host named Chad.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a7d28f5a-6996-45ff-8b97-9d4aa89228de', 'Word: Modern Art
Definition: A banana taped to a wall that sold for $120,000, confirming that money laundering is indeed a fine art.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('3bc0af09-0ccf-4ffb-a01f-e1f118eb4fb3', 'Word: Electric Vehicle
Definition: A silent car powered by batteries that makes you feel green while you search for a charger in a dark Walmart parking lot.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('ac4ba0ab-d5c3-4ac9-98a7-105a52b84b98', 'Word: Subscription Model
Definition: A business strategy where you pay $9.99 a month forever for a service you used once to watch a documentary about a cult.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('c0f16622-3f09-4a5d-b470-6c75c2fecb70', 'Word: Influencer
Definition: A person who has convinced millions of strangers that their life is interesting because they have a ring light and a gluten allergy.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('2530ae49-ba34-4fc6-9400-f23a8a23e36c', 'Word: Corporate Wellness
Definition: A mandatory yoga class designed to distract you from the fact that your salary hasn''t kept up with inflation since 2012.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('081364b7-8ab2-4149-982a-7114538aec75', 'Word: Side Hustle
Definition: A second job you need to pay for the rent on the apartment you only sleep in because you''re working your first job.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('2b2df393-82ed-4568-af4b-45e14474d50d', 'Word: QR Code
Definition: A pixelated square that replaced menus because restaurants wanted you to experience the joy of zooming in on a PDF on your phone.', '[dictionary] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('7d1a78a8-b4c2-4142-a06e-829397d4d617', 'I love airline pilots. They get on the intercom and speak in that low, sleepy voice. They sound like they are driving a golf cart, not flying a 200-ton metal tube through a thunderstorm.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('57f8c002-8698-4089-aa0b-abb008cae2ae', 'I hate modern menus. QR codes are a joke. I don''t want to scan a barcode, wait for a PDF to load on my slow internet, and zoom in on a screen just to see how much a burger costs. Give me a piece of paper.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a883b96f-fed3-4ec8-92dc-62261a3f9b20', 'Went to a fancy cocktail bar. The drink took 20 minutes to make, had a single giant ice cube, and came in a glass that looked like a lightbulb. I just wanted a beer, not a chemistry demonstration.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('b9f66dd3-b60d-45e0-ae47-ea08f4081136', 'I read reviews for everything. I saw a one-star review for a national park. The guy wrote: ''Too many rocks. Very steep.'' It''s the Grand Canyon, Dave. What did you want? An escalator?', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('d735f08f-5783-4121-ba23-906170b8382e', 'Food delivery apps are out of control. I ordered a sandwich. The sandwich was $8, the delivery fee was $4, the service fee was $3, the driver tip was $5. By the time it arrived, I had paid $20 for a piece of ham.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('b9c25a3f-d7f4-4e3f-b43d-e0e037299716', 'LinkedIn is the only social network where people brag about working on Saturdays. ''Thrilled to announce I spent my weekend updating a spreadsheet! #Blessed #Grind.'' Seek help.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e99d1a21-74cb-4070-be6e-7c48ee5e0ceb', 'voicemail is dead. If you leave me a voicemail, I assume you''re calling from 1998. Send a text. I don''t want to dial a number, enter a passcode, and listen to a robotic voice just to hear you say ''Hey, call me.''', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('f17950d9-a910-4253-9e67-6c47103f5642', 'Why do hotel beds have 8 pillows? I don''t need a nest. I spend the first 10 minutes of my stay throwing pillows on the floor like a dog clearing its territory.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('45f9ba2b-86d9-497e-8b15-36cbb13d6322', 'Being in a group chat is like being in a meeting you can''t leave. You look at your phone and you have 84 unread messages, and it''s just two of your friends arguing about where to buy socks.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('96ccd4ff-391c-4947-86d2-0781da341ff5', 'Going to the grocery store hungry is a financial disaster. I went in for milk and came out with a pineapple, three frozen pizzas, and a microplane grater. I don''t even know what a microplane grater does.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('9d2cd3a3-8600-4ecf-8a7b-daf059002795', 'My password security is ridiculous. I need an uppercase letter, a lowercase letter, a number, a special character, and a line of ancient Greek poetry. And then it tells me, ''Password cannot contain joy.''', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('28db38dc-cbaa-4a6b-8466-685bc9dc5ca6', 'Dentists are the only professionals who ask you questions while their hands are in your mouth. ''So, how''s your summer going?'' ''Arrghggh.'' ''Oh, really? That''s nice.''', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('39e5e79b-7bb0-4372-8b41-8456f9144b1b', 'Why do weddings start at 4 PM but the reception doesn''t start until 7 PM? What am I supposed to do for three hours in a suit? Wander around a pharmacy?', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('1af5558e-7350-42bb-86f1-71123ca33427', 'My wife bought a sign that says ''Gather'' and put it in the dining room. Just in case our friends came over, sat in the hallway, and needed instructions on where to assemble.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a88bde50-70fd-45a5-8201-ecb13806c77f', 'We bought a smart thermostat. It learned our schedule. Now it turns the heat off at 10 PM. I have to sit in my own living room wearing a ski mask, trying to trick my wall into thinking I''m still alive.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('c1c21bb2-11a7-4a13-b348-3b5ecacf30ef', 'My phone tracking report is depressing. It tells me my screen time went up 12% this week. I don''t need a weekly report card from my pocket telling me I''m lazy.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('dd131cfa-c6d0-4e35-86b2-4a04f586d04c', 'Going to a fancy cocktail bar. The drink took 20 minutes to make, had a single giant ice cube, and came in a glass that looked like a lightbulb. I just wanted a beer.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('2d63d903-734b-4fb9-9b12-399dee007cb6', 'We bought a smart thermostat. It learned our schedule. Now it turns the heat off at 10 PM. I have to sit in my own living room wearing a ski mask, trying to trick my wall into thinking I''m still alive.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('30bae26d-1169-42a9-a2a2-ab6141e8611a', 'I read reviews for everything. I saw a one-star review for a national park. The guy wrote: ''Too many rocks. Very steep.'' It''s the Grand Canyon, Dave. What did you want? An escalator?', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('b0272831-bbd7-4b37-bdb4-8bcdb6b59653', 'I hate packing for trips. I always pack like I''m going to start a completely new life. ''Yes, I definitely need three formal shirts and a pair of running shoes for a weekend in Ohio.''', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a6dc6fa5-395c-4484-b097-c003358bd0a0', 'Why do weddings start at 4 PM but the reception doesn''t start until 7 PM? What am I supposed to do for three hours in a suit? Wander around a pharmacy?', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('842549fd-96e4-4be7-8014-e40ca63e3f74', 'My wife bought a sign that says ''Gather'' and put it in the dining room. Just in case our friends came over, sat in the hallway, and needed instructions on where to assemble.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('03f9e0f9-06fe-40f6-bc3f-40364415f545', 'I hate self-checkout. The machine always says, ''Unexpected item in bagging area.'' It''s a bag of chips, machine. What did you expect? A grand piano?', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('8d1997e5-73d2-4b3c-9f14-10261798f1e2', 'Being in a group chat is like being in a meeting you can''t leave. You look at your phone and you have 84 unread messages, and it''s just two of your friends arguing about where to buy socks.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('c6b0af91-3bd0-4696-94ed-ae34f3b7d776', 'Why do hotel beds have 8 pillows? I don''t need a nest. I spend the first 10 minutes of my stay throwing pillows on the floor like a dog clearing its territory.', '[roast] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('dd9274b9-1bbf-4657-b2e7-b1e87289d042', 'I finally deleted all my dating apps. I realized I was looking for love in all the wrong places. Now, I just wander around the local graveyard waiting for a rich widow to cry.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a6377fae-24d5-4064-b188-bae2a784fc13', 'Getting older is just a constant series of body betrayals. First your metabolism slows down, then your back goes out... and then one day you make a noise standing up from the couch that sounds exactly like a dying walrus.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('82ff3c12-0b9e-47be-b2d3-102ca2325d7c', 'Whenever an automated voice says, ''Your call is very important to us''... I know for a fact I am about to spend 45 minutes listening to royalty-free jazz before a stranger hangs up on me.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('912ae41c-10ed-4842-88d2-6dc591a98aa8', 'Inflation is getting so bad that I can''t even afford to have anxiety about it anymore. I went to buy a dozen eggs today and had to put down my car as collateral.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('4f9a5c90-c974-41a6-bea1-87bc375e0783', 'Everyone says you should go to therapy to fix your problems. I went for a year. Now I still have all the exact same problems, but I pay $200 an hour to complain about them using clinical vocabulary.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('076f6a07-fa02-4f0e-b3dd-df194b401786', 'When you''re 21, you can drink 15 shots of tequila, sleep in a bush, and wake up ready for a marathon. I''m in my 30s now. If I eat a piece of bread too fast at 8 PM, I need three days of bed rest.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('5540d7ab-cb71-4c74-9172-e036a112a61f', 'I love looking at wedding registries. It''s so beautiful to see two people commit to spending the rest of their lives together... and demanding I buy them a $400 toaster just to witness it.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('7050bfcc-1721-4127-bc1e-8129e00b9216', 'I hate the self-checkout lane at the grocery store. I don''t work here. If I''m scanning my own items and bagging my own groceries, I expect a W-2 and dental benefits.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('239bbeac-f660-4ecb-9ba1-370d989e7f64', 'Sitting in rush hour traffic is a great way to catch up on podcasts. It’s also a great way to fully mentally prepare for driving your sedan off an overpass.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('9117af44-40b7-47d4-a711-d780478b7045', 'I started intermittent fasting recently. It''s a great diet where you only eat during an eight-hour window. Unfortunately, during that window, I eat like a bear preparing for a winter.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('1240c08b-3214-41cb-b68f-65087e866529', 'I hate going to the dentist. They look inside your mouth and ask, ''Have you been flossing?'' Yes, of course. I also regularly update my software and read the terms and conditions.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('aa01d5f1-f9b9-4876-9608-a22b1b1b469d', 'I bought a smart fridge. Now, every time I open it, it judges me. It sent an email to my phone saying: ''We noticed you bought a block of cheddar. Are we okay?''', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('b454a9c1-c434-4418-a206-2d7102cc9f1c', 'I don''t get hiking. You walk up a mountain, look at some trees, and then walk back down. It''s just walking, but with a higher chance of falling off a cliff.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('4d5d4e65-58a4-43f3-95bf-79b858880838', 'I tried to buy a house. The bank asked for a 20% down payment, three years of tax returns, and my firstborn child. I just wanted a one-bedroom apartment, not to join a medieval guild.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('7a053919-615d-4e60-9d36-16b2e9577527', 'I hate packing for trips. I always pack like I''m going to start a completely new life. ''Yes, I definitely need three formal shirts and a pair of running shoes for a weekend in Ohio.''', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('69d7d5ce-4f9e-4b00-b0d6-65ff07f4247c', 'Why do we still have voicemail? If I don''t answer your call, send a text. Do not make me listen to 15 seconds of robot instructions just to hear you say ''Call me back.''', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e17a54dd-4a4d-4b35-91c3-88d24ccf1b28', 'I went to a fancy cocktail bar. The drink took 20 minutes to make, had a single giant ice cube, and came in a glass that looked like a lightbulb. I just wanted a beer, not a chemistry demonstration.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('66e6b8f7-cc44-4ee0-b4e4-873434f9507f', 'My phone tracking report is depressing. It tells me my screen time went up 12% this week. I don''t need a weekly report card from my pocket telling me I''m lazy.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('dd92b308-ef0c-4fc1-9bbe-196fa52afa84', 'I tried to cancel my cable subscription. The customer rep acted like I was divorcing them. ''But what about the sports package?'' I don''t watch sports. ''But we can give you HBO for $2!'' I don''t care, let me go!', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('17f95ea4-0308-4eb9-abf0-09e9173c9275', 'Why is modern packaging so hard to open? You need scissors to open the package of scissors you just bought. It''s a cruel joke from the tool manufacturers.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('e21cc74c-f75a-49e3-a657-063b6c663b78', 'I tried to buy a romantic candle. It was scented ''tobacco and vanilla.'' Why would I want my bedroom to smell like a grandfather who got lost in a bakery? If I''m paying $30 for a candle, I want it to smell like pure desperation and bad decisions.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('8318c49a-08ba-4216-88c8-54bbd3046b19', 'Polyamory is just an elaborate scheduling system for people who want to disappoint multiple partners simultaneously. It''s not a relationship; it''s a project management system where everyone gets a performance review at 2 AM.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('7476125d-aaa0-41ee-b985-ce20720a3c92', 'Corporate drug testing is ridiculous. They check if I smoked weed three weeks ago. Why do you care what I do on my own time? I''m entering data into a spreadsheet, not performing open-heart surgery. Being high is the only way to survive a Tuesday afternoon meeting about synergy.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('0fe78186-fec6-4faa-b6d6-d07f6a9e15e0', 'My friend told me she started an OnlyFans to pay off her student loans. Honestly, it''s the only honest business model left. You show your feet, you get paid. Compare that to corporate life, where you show your soul for 40 years and get a plastic pen when you retire.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('a7733934-7e31-46ff-8a10-7cef2183d2b4', 'Why are there so many pharmaceutical commercials during sports games? Every three minutes it''s: ''Ask your doctor if your heart is healthy enough for sex.'' If my heart is that fragile, sex is the least of my concerns. I''d be trying to survive walking up the stairs, not planning a weekend in a bathtub on a hill.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('d8629579-46ba-4406-9afb-b4ea4f2567b4', 'I saw a Tinder profile that said: ''Must be over 6 feet, make six figures, and have a good relationship with your mother.'' That''s not a dating profile; that''s a job posting for a guy who will eventually murder you for the insurance money.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('6cb17077-c2c0-4968-b385-250d22418953', 'Every tech bro in Silicon Valley is microdosing mushrooms. They say it makes them ''more focused.'' Back in my day, we called that ''getting high at work.'' You''re not optimizing your flow state, Kevin. You''re just staring at a spreadsheet of a giraffe.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('2c19d247-7d51-4f27-98e0-235c52d83a14', 'Sex education in high school was pure terror. They showed us photos of diseases that looked like alien landscape photography. The message was clear: ''If you touch another human being, your body will rot.'' No wonder we''re all in therapy.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('78f34fbc-0a93-48eb-8844-5deafdcb2a97', 'I hate going to the dentist. They look inside your mouth and ask, ''Have you been flossing?'' Yes, of course. I also regularly update my software and read the terms and conditions.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('8f832f27-1281-4b81-a3ac-92818d3e6fc7', 'I bought a smart fridge. Now, every time I open it, it judges me. It sent an email to my phone saying: ''We noticed you bought a block of cheddar. Are we okay?''', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('84f608d9-a7d6-432e-aa99-afb1b8a8f173', 'I don''t get hiking. You walk up a mountain, look at some trees, and then walk back down. It''s just walking, but with a higher chance of falling off a cliff.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('73488daa-0d0e-4d47-a1ec-e31151ccb070', 'I tried to buy a house. The bank asked for a 20% down payment, three years of tax returns, and my firstborn child. I just wanted a one-bedroom apartment, not to join a medieval guild.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('fc59a10e-1afc-474f-91ba-f4916f668b37', 'Why do we still have voicemail? If I don''t answer your call, send a text. Do not make me listen to 15 seconds of robot instructions just to hear you say ''Call me back.''', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('62742295-2365-4563-a2c9-4909a9603eff', 'I went to a fancy cocktail bar. The drink took 20 minutes to make, had a single giant ice cube, and came in a glass that looked like a lightbulb. I just wanted a beer, not a chemistry demonstration.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('3fb67bc7-4173-4d7a-9b16-8f6912b30542', 'My phone tracking report is depressing. It tells me my screen time went up 12% this week. I don''t need a weekly report card from my pocket telling me I''m lazy.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('74aaa5eb-7511-4e65-9b7f-d318eaf8c476', 'I tried to cancel my cable subscription. The customer rep acted like I was divorcing them. ''But what about the sports package?'' I don''t watch sports. ''But we can give you HBO for $2!'' I don''t care, let me go!', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('3ff64fa2-0878-4ce0-bd32-3da9a6759cb6', 'Why is modern packaging so hard to open? You need scissors to open the package of scissors you just bought. It''s a cruel joke from the tool manufacturers.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('32e246ea-a03b-4a78-aafb-8afd0341ba2a', 'Sex ed in high school was pure terror. They showed us photos of diseases that looked like alien landscape photography. The message was clear: ''If you touch another human being, your body will rot.'' No wonder we''re all in therapy.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('f12d05c7-1cb7-46e4-ab67-94bc532ba07b', 'I saw a Tinder profile that said: ''Must be over 6 feet, make six figures, and have a good relationship with your mother.'' That''s not a dating profile; that''s a job posting for a guy who will eventually murder you for the insurance money.', '[standup] Seed', 100, 0);
INSERT INTO jokes (id, text, premise, kills, bombs) VALUES ('041a4062-3f48-4cd5-b823-7917f1f4a2d2', 'My friend told me she started an OnlyFans to pay off her student loans. Honestly, it''s the only honest business model left. You show your feet, you get paid. Compare that to corporate life, where you show your soul for 40 years and get a plastic pen when you retire.', '[standup] Seed', 100, 0);
